language: python
branches:
  only:
  - source
install:
- pip install pelican ghp-import html5lib BeautifulSoup4 disqus-python markdown markdown-tweetable
before_script:
- pelican-themes -i ./theme/pelican-elegant
script:
- make publish github
env:
  global:
  - secure: TgDoskiGyMRjWhJLhGMfRrqVk7OzBb3JpU/8btukfBlHP358sPOgFHnEDLbMCG83+ZiAjaejKN+VawM1iHOHnhDEwFb/x4Rt7/AIskgnbhE3F6hgK0KYHKZ1qebR0gcfhdcCuq99B84uNZWQvtvuYlEsS2l1Q/YTqdh43QC8sS8=
