language: python
branches:
  only:
  - source
install:
- pip install pelican ghp-import html5lib BeautifulSoup4 disqus-python markdown
before_script:
- wget https://github.com/talha131/pelican-elegant/archive/V1.3.zip -O ./elegant.zip
- unzip elegant.zip -d ./elegant
- mv elegant/pelican-elegant-1.3/* elegant/
- pelican-themes -i ./elegant
- pelican-themes -l
script:
- make publish github
env:
  global:
  - secure: TgDoskiGyMRjWhJLhGMfRrqVk7OzBb3JpU/8btukfBlHP358sPOgFHnEDLbMCG83+ZiAjaejKN+VawM1iHOHnhDEwFb/x4Rt7/AIskgnbhE3F6hgK0KYHKZ1qebR0gcfhdcCuq99B84uNZWQvtvuYlEsS2l1Q/YTqdh43QC8sS8=
