dist: xenial

addons:
  snaps:
  - hugo

branches:
  only:
  - source
git:
  depth: false
install:
- pip install Pygments
script:
- hugo
after_success:
- cp content/extra/CNAME public/CNAME
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GH_TOKEN # Set in travis-ci.org dashboard
  target-branch: master
  fqdn: shaunagordon.com
  committer-from-gh: true
  verbose: true
  on:
    branch: source
