language: python
branches:
  only:
  - source
install:
- pip install pelican ghp-import html5lib BeautifulSoup4 disqus-python markdown
before_script:
- wget https://github.com/talha131/pelican-elegant/archive/V1.3.zip -O ./elegant.zip
- unzip elegant.zip -d ./elegant
- mv elegant/pelican-elegant-1.3/* elegant/
- pelican-themes -i ./elegant
- pelican-themes -l
script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- make publish github
env:
  global:
  - secure: E/7Sh5BPDFiUN9vS9rOmONCxnifA/B4Bdv5ia4DQ49ZfJX2T9WVdgb+K1/nqXD5kUs8A2kC2pHrxEKwDsUpiAteYBuILLaR+gKVTNH8bJrKfMt0nYyv/H7MOs5zSRwFiv4WSkDFJdKRGo9dBChktEnzqcrjJfUW9qa28sqFRbrVTyoGms9wNJiVgfQSR58lf1wpIcy4HcFgALwLmbTTIMqmMPptriCmotr31BP6ntq0hfluvxJGdlgCQKeAWRsie2YxhdYeeck5cpexQLTcoN1xdt8SEh4pOz8XcxT0ezJfsx933/2nhf8MzK8EK9GwkBPvr2CbqopouQ9KWpl8F0Tlb2Djvo9yKTrPYurUF353CwP7NEWBzINvnLxn7YmDjkBnfY08YCy9RnMEqdKp2mSns/8i+Szd5jF2nA4MYnR1FNCVZuhTaE67Nz0AeV1wZA8FboQXiwteHd3MzgP8gX5Wr5liRgzJX24OnudNiRv/VYuxOCwPv3KHs2XNdTWXTuKey8XpCLWRAX7WpL96p5D4/dDyQax1jJJOTXoNjb1uJ9s9yGgmglG2loMV1poJQ/zRAenR/SnWgG2G2slseqTrBuRVHEnpFdUm5r1fTZ9ols7PvrX6BpRs3fqpZVP3EemTL5FuOXOIYvuGWUI8nQz11fPQ+68HqXsreMkb9A28=
