language: python
branches:
  only:
  - source
install:
- sudo apt-get install -y pandoc
- pip install -r requirements.txt
before_script:
- pelican-themes -i ./theme/elegant
- pelican-themes -l
- cd plugins/extract_toc && git remote add test https://github.com/bnice5000/pelican-plugins.git && git fetch test a1fbd885d37f9cf6877af68bdfb1a2680ae48215 && git checkout FETCH_HEAD
script:
- make publish github
env:
  global:
  - secure: TgDoskiGyMRjWhJLhGMfRrqVk7OzBb3JpU/8btukfBlHP358sPOgFHnEDLbMCG83+ZiAjaejKN+VawM1iHOHnhDEwFb/x4Rt7/AIskgnbhE3F6hgK0KYHKZ1qebR0gcfhdcCuq99B84uNZWQvtvuYlEsS2l1Q/YTqdh43QC8sS8=
