language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
before_script:
- wget https://github.com/talha131/pelican-elegant/archive/V1.3.zip -O ./elegant.zip
- unzip elegant.zip -d ./elegant
- pelican-themes -i ./elegant
script:
- make publish github
env:
  global:
    secure: Djo9AG197gK3CkJjiH9fnNz2iaPZhOE6BYc9zfeQnT1b0q9DuDpubaundxZ7UUE7QyazDGwEyohgFRStWVFg0ZNrQYl4hw0BFuRmD6DXSk2joPa/OyTmM7gy5NsOXuIUrjQqa5H+7ak4tVAi9f37RHgmMflR+MiLS2DhmHMzWYHlFCUbTx7OtfDHppL5hXsrSwxh/FiuyQ84vdjOAmBhg9YeDDn+vwK2WRHSUTBHIzMe1NeROI2ZMPvzK0oPTlcZHYUFnNuAJfByQek8mFIgJ0FQ4DLYhr2kwnfbB1JdFYR1y5b1bp3kyXGE0535vD+1xw53vKRE0XsD8nwFl4y35xReZUSjQmEr55diRF329W2c70Eh8dz9WdMLjdx182MbtVkkXUmECGdCrUIXbOfgVwfXBZqRN3ndLB2do+qU4HQyJvj7wqWEF5BcDjDHC3veJnr23UPLOEOterf2lZlIXX0Uy4Kz/7746CVuy7gWW2FnnvjfKEGQPrx1UAUYcRZ1V39uq8/AH7eU0zkiCoiM75angbqynZskRI4h1De/epD4LmhNWZRjHaZMpHPj7pgeUregVLYtML6rgjuHhgETy7B4Dk2tNBR9i5bxG6x1sTj57GKZshmwO1wvz19hYG+hQjzYoyACc088h1DkfA+8sw1p8TV7mg3FiipWnx4Y60k=
