language: python
branches:
  only:
  - source
install:
- pip install pelican ghp-import html5lib BeautifulSoup4 disqus-python markdown
before_script:
- wget https://github.com/talha131/pelican-elegant/archive/V1.3.zip -O ./elegant.zip
- unzip elegant.zip -d ./elegant
- mv elegant/pelican-elegant-1.3/* elegant/
- pelican-themes -i ./elegant
- pelican-themes -l
script:
- make publish github
env:
  global:
    secure: syXE9ZLzvDjkOimU7VpwSXdUwVdzKnIMxeNHbpuuQp6TgsBBDSRGebcfn9bomv2Gq/phreucBezRhHVzEmfY9VGMuNZj8PoTXcHg3hf5x/y9ZvPbtxa1FlTKOpljEW+yO2/3lZkCByuOYx1QL1RGw84FHR8tZ80EY0tEuvNfTqXqDX88tLJESBriXHWRnBf8ROVVpgUQg32t2rdQEmwrBRvzgRQl2+M2fNZsJG0KdUKJd6HhFJfCwzmGw/28YY96iPpAfC8TudmMr1GPp2kKSMpXFHl0HiIyEbc6Fkg6Vokxes382g5gaQGeRXgZD63/ttAemJhYRBkyaQ3rWGH57AkNEepqeWWJGWDcCrmqnZxjdoB1w/YfCYqMclhtPqsC7qf68iNh4SJGlMj7QvnK+bbLkCus63Y2CLTg5jWsyhOnYvXRaOCrOlWzvB32nXCiWjH99IYkfq/CbUbOCI7zFMC2URSX0YMq+o0B8Lb2CE7qj+9eYN/5+R54u6VLJbbgQ1zXwMTEO8Voj2ol13tIDxnKrqF14sVvILmiNC6/17vVFJeD/BlXXut3rczwgvfVViIV0jvLzWwxgs6/XfSTri9ClDknlTXwyDo6EYsge/4qSkuD++psaEoCDpEPfHAFkWtjvpSKiasl0Ply3B/cKw3B4E57Fpl96s+3zq1xjYo=
