baseURL = "http://shaunagordon.com/"
languageCode = "en-us"
title = "I Make Things"
theme = "dream-plus"

pygmentsCodeFences = true
pygmentsUseClasses = true

disableKinds = [
  # "taxonomy",
  # "taxonomyTerm"
]

enableEmoji=true

paginate = 10

[permalinks]
  posts = ":year/:month/:day/:slug/"

[params]
  author = "Shauna Gordon"
  description = "I Make Things"
  motto = "I Make Things"
  avatar = "/images/avatar.png"

  contentType = "posts"
  itemsPerPage = 10
  enableColorBG = true
  enableToc = true
  enableTags = true
	enableCategories = true
  
  linkedin = "gordondev"
  github = "ShaunaGordon"
  gitlab = "shauna"
  email = "shauna@shaunagordon.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"