baseURL = "http://shaunagordon.com/"
languageCode = "en-us"
title = "I Make Things"
theme = "dream-plus"

pygmentsCodeFences = true
pygmentsUseClasses = true

enableEmoji=true

paginate = 10

[permalinks]
  posts = ":year/:month/:day/:slug/"

[params]
  contentType = "posts"
  itemsPerPage = 10
  enableColorBG = true
  enableToc = true
  enableTags = true
	enableCategories = true

  [params.author]
    name = "Shauna Gordon"
    description = "I Make Things"
    motto = "I Make Things"
    avatar = "/images/avatar.png"

  [params.features]
    twitterEmoji = true
    toc = true

  [params.tags]
    enabled = true

  [params.categories]
    enabled = true

  [params.series]
    enabled = true

[social]
  linkedin = "gordondev"
  github = "ShaunaGordon"
  gitlab = "shauna"
  email = "shauna@shaunagordon.com"