baseURL = "http://shaunagordon.com/"
languageCode = "en-us"
title = "I Make Things"

# pygmentsCodeFences = true
# pygmentsUseClasses = true

enableEmoji=true

[pagination]
  paperSize = 10

[module]
  [[module.imports]]
    path = "github.com/ShaunaGordon/hugo-lucid-dream"

[permalinks]
  posts = ":year/:month/:day/:slug/"

[params]
  contentType = "posts"
  itemsPerPage = 10
  enableColorBG = true
  enableToc = true
  enableTags = true
	enableCategories = true
  goatcounter = "gordondev"

  [params.author]
    name = "Shauna Gordon"
    description = "I Make Things"
    motto = "I Make Things"
    avatar = "/images/avatar.png"

  [params.features]
    twitterEmoji = true
    toc = true
    search = true
    coverDir = "/images/covers/"

  [params.tags]
    enabled = true

  [params.categories]
    enabled = true

  [params.series]
    enabled = true

  [params.background]
    gradients = [["#3e5151", "#decba4"],["#333333","#dddddd"],["#555B6E","#326F85","#D5BBB1","#440D0F"],["#1C3E4A","#B0B5B3","#F15855","#2F0A28"]]

[social]
  linkedin = "gordondev"
  github = "ShaunaGordon"
  gitlab = "shauna"
  email = "shauna@gordons.me"
  resume = "//resume.shaunagordon.com"
  buymecoffee = "#buy-me-coffee"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    # hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'vulcan'
    tabWidth = 4

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[outputs]
  home = ["html", "rss", "json"]
