baseURL = "http://shaunagordon.com/"
languageCode = "en-us"
title = "I Make Things"

[module]
  [[module.imports]]
    path = "github.com/ShaunaGordon/hugo-dream-plus"

pygmentsCodeFences = true
pygmentsUseClasses = true

enableEmoji=true

paginate = 10

[permalinks]
  posts = ":year/:month/:day/:slug/"

[params]
  contentType = "posts"
  itemsPerPage = 10
  enableColorBG = true
  enableToc = true
  enableTags = true
	enableCategories = true
  goatcounter = "gordondev"

  [params.author]
    name = "Shauna Gordon"
    description = "I Make Things"
    motto = "I Make Things"
    avatar = "/images/avatar.png"

  [params.features]
    twitterEmoji = true
    toc = true

  [params.tags]
    enabled = true

  [params.categories]
    enabled = true

  [params.series]
    enabled = true

  [params.background]
    gradients = [["#3e5151", "#decba4"],["#333333","#dddddd"]]

[social]
  linkedin = "gordondev"
  github = "ShaunaGordon"
  gitlab = "shauna"
  email = "shauna@gordons.me"
  resume = "//resume.shaunagordon.com"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
